### ISSUE TITLE
Find a study on ImmunoSeq to use as a test case.

### ISSUE THREAD

**Issue by bcorrie** [sfu-ireceptor/AIRR-seqAA#1]
One of the first steps is to log in to ImmunoSeq and find a test study to use... Best to use something which rich tags and probably use more than one study as an example...

**Comment by lfunderburk** [comment]
@nknoetze  can you add a doc with the ID's you chose for future references (or comment here)

**Comment by lfunderburk** [comment]
project Ids:
b2bc098c-da25-4e98-80d1-161f59d856e0
f06168cd-ee60-4174-9444-995b2ec21e2f
35ee1166-bfba-40a9-871b-2c6d6ab7f1c9

these two have already been downloaded
5eaca36e-c0b9-4be5-aeaa-bc1d230af791
7d742a21-6978-41c5-91a5-d43819011606
