### ISSUE TITLE
Install an iReceptor Turnkey on CC VM

### ISSUE THREAD

**Issue by bcorrie** [sfu-ireceptor/AIRR-seqAA#4]
Turnkey github is here: https://github.com/sfu-ireceptor/turnkey-service-php

Can access the VM as per the instructions in the "compute-canada-tech-support" Slack channel

**Comment by lfunderburk** [comment]
@bcorrie  reports: 

> installed both an ireceptor Turnkey and the git repo on our project VM.
> Both the CWL workflows ran if run them as root on the VM
> Needed to do a sudo -s
> If we can get an AIRR Repertoire JSON file from the Adaptive metadata, then we can load it into the iReceptor repository.

**Comment by bcorrie** [comment]
Note: Added ubuntu user to docker group, so sudo no longer required.

**Comment by bcorrie** [comment]
Closing this issue, as it is complete...
