### ISSUE TITLE
Download data from ImmunoSeq study

### ISSUE THREAD

**Issue by bcorrie** [sfu-ireceptor/AIRR-seqAA#5]
Download the data chosen in #1

**Comment by lfunderburk** [comment]
Similar to issue #1  - add id's here and I can download TSV for JSON conversion and parsing field names.

**Comment by lfunderburk** [comment]
[Doc](https://github.com/sfu-ireceptor/AIRR-seqAA/blob/master/README.cwl.md) and [scripts](https://github.com/sfu-ireceptor/AIRR-seqAA/tree/master/cwl) added by @mr-c  
here

**Comment by nknoetze** [comment]
project Ids:
b2bc098c-da25-4e98-80d1-161f59d856e0
f06168cd-ee60-4174-9444-995b2ec21e2f
35ee1166-bfba-40a9-871b-2c6d6ab7f1c9

these two have already been downloaded
5eaca36e-c0b9-4be5-aeaa-bc1d230af791
7d742a21-6978-41c5-91a5-d43819011606

**Comment by lfunderburk** [comment]
Closing as pipeline is ready to download data.
