### ISSUE TITLE
README Feedback

### ISSUE THREAD

**Issue by lisancao** [sfu-ireceptor/AIRR-seqAA#9]
Very informative readme, the links and images make it incredibly resourceful and helps to summarize the important parts of the project. Also love that you put the team members at the beginning instead of the end like many others do. Helps highlight that this is a university affiliated project for sure. 

Some personal notes I have (optional): 
- So some bolding or italicizing of certain text points for readability, and perhaps adding a note of whether you are open to collaborators. Particularly the parts where you emphasize the repository will be fully publicly available

Fantastic job!

**Comment by lfunderburk** [comment]
Thank you @lisancao !

**Comment by lfunderburk** [comment]
Sorry - meant to add a comment before closing. 
Ok, will need to discuss with members moving forward whether we want to open for continuing work.
